### ISSUE TITLE
Voucher support?

### ISSUE THREAD

**Issue by SupaYoshi** [mixmint/opnsense-captive-portal-template#10]
currently the template only supports username and password login, would it be possible to set vouchers to login?
Kind regards

**Comment by mixmint** [comment]
The template supports all authentication methods available in OPNsense. Actually, it doesn't even depend on this template because it is implemented on the API side in Captive Portal. However, Voucher support is configured differently than, for example, pfSense. In OPNsense, the Voucher consists of a login and password, while in pfSense it consists only of a key.

**Comment by SupaYoshi** [comment]
Hi Mixmint, what you are saying might be true very well. But my system is set like this, and I have no voucher coming up but only username and password:

https://prnt.sc/7hVYqVho0FGe
https://prnt.sc/I9UW7w8Genb8

**Comment by mixmint** [comment]
I don't think you have generated vouchers. Use Create vouchers in Vouchers. When generating a new list of credentials, a CSV file will be downloaded containing the logins and passwords of the vouchers that Captive Portal has just set.
