### ISSUE TITLE
Customization of Portal Page

### ISSUE THREAD

**Issue by dpsguard** [mixmint/opnsense-captive-portal-template#2]
Hi mixmint, Thanks for sharing this template. Are you available to customize it for my needs against suitable compensation for your time? Thanks

**Comment by mixmint** [comment]
Hi. Yes, I can take care of it. Ultimately, I want to slightly simplify the resulting HTML in this template, I will try to make it more universal. What do you need in your project?

**Comment by dpsguard** [comment]
Thanks my friend.

 

My requirement is simple. Need to have a simpler page for Guest Wi-Fi wherein guest simply clicks a button to Proceed. There are terms and conditions text written above the Proceed button. Better to also include a check mark box just before the text starts (below the welcome line). So Guest click on check mark box to fill the box and then scrolls down and clicks on Proceed button to be redirected to a webpage and then is able to surf the internet.

 

Below the button, I need to add two text lines for company name and address. No username / password, just a click thru button to accept the terms of service.

 

There can be option to upload a background and the logo. The button text (Proceed or Login) and button color should be selectable.

 

Very best,

**Comment by mixmint** [comment]
Ok, it took me a while... thanks for your patience. I made some changes, fixed some bugs, implemented some improvements. This is currently a rewritten template. I haven't tested everything yet, so it may happen that something doesn't work perfectly. If you spot a mistake, I will be grateful for feedback. However, when answering questions and needs:

If you want to use a "simple" authentication method, i.e. "without authentication", all you need to do is select no option in the "Authenticate using" field in the edition of your Captive Portal zone (let's call it CP). The template supports this view by design. Just starting the CP zone will cause that computers/devices connecting to the Internet will have to start a session in the CP service, hence the first thing they will "see" is a properly rendered CP page.

The company name, address, and additional information have been entered into the language files as a key object, so there can be as many of them as you decide. Two containers have been launched, in which the elements of these objects are embedded, the first is under the button ("isp_info"), the second is in the footer ("footer_isp_info"). Depending on which key you will use, then information about your company will be there. The same applies to the content of the button (or almost any text on this template) - everything is in the language files, you can set it yourself.

The logo can be saved, for example, in the images directory and then in settings.json in the "logo" key indicate its path "images/example_file_name.png". Colors (almost every css definition), popup settings, files and language variables are also defined in settings.json.

I did not plan to embed the image as the background of the CP template due to minimizing the load on the CP server, of course I can post it as an alternative to the classic color but as a separate release.

A change in the view itself - "checkbox under welcome" - also in a separate release.

It will take me about 2 more days.

**Comment by dpsguard** [comment]
Hi mixminit. Sorry this took a long time to get back. The email had landed in junk folder somehow and I did not check junk folder until few minutes ago.

 

For now, I had used a simple page and will love to use a better page like designed / created by you.

 

Few questions I have:

 

1.	Will it allow a redirect page after a Guest accepts terms of service and clicking on login or Proceed button? Example, we send them to www.domain.org/whatisnew.html <http://www.domain.org/whatisnew.html> 
2.	Do you see any issues with not using https / SSL cert? It seems to work fine now with default redirection to port 8000 using http.
3.	Is there a way to add a URL for detailed terms of service and allow that URL to be reachable without someone having to click the portal proceed button?
4.	Will this allow hundreds of users trying to connect and thus serving many portal pages at the same time? I have quad core Xeon CPU and 12GB RAM in an old Supermicro server.

Thanks so much.

 

From: mixmint ***@***.***> 
Sent: Friday, July 28, 2023 9:26 PM
To: mixmint/opnsense-captive-portal-template ***@***.***>
Cc: dpsguard ***@***.***>; Author ***@***.***>
Subject: [SPAM] Re: [mixmint/opnsense-captive-portal-template] Customization of Portal Page (Issue #2)

 

Ok, it took me a while... thanks for your patience. I made some changes, fixed some bugs, implemented some improvements. This is currently a rewritten template. I haven't tested everything yet, so it may happen that something doesn't work perfectly. If you spot a mistake, I will be grateful for feedback. However, when answering questions and needs:

If you want to use a "simple" authentication method, i.e. "without authentication", all you need to do is select no option in the "Authenticate using" field in the edition of your Captive Portal zone (let's call it CP). The template supports this view by design. Just starting the CP zone will cause that computers/devices connecting to the Internet will have to start a session in the CP service, hence the first thing they will "see" is a properly rendered CP page.

The company name, address, and additional information have been entered into the language files as a key object, so there can be as many of them as you decide. Two containers have been launched, in which the elements of these objects are embedded, the first is under the button ("isp_info"), the second is in the footer ("footer_isp_info"). Depending on which key you will use, then information about your company will be there. The same applies to the content of the button (or almost any text on this template) - everything is in the language files, you can set it yourself.

The logo can be saved, for example, in the images directory and then in settings.json in the "logo" key indicate its path "images/example_file_name.png". Colors (almost every css definition), popup settings, files and language variables are also defined in settings.json.

I did not plan to embed the image as the background of the CP template due to minimizing the load on the CP server, of course I can post it as an alternative to the classic color but as a separate release.

A change in the view itself - "checkbox under welcome" - also in a separate release.

It will take me about 2 more days.

**Comment by mixmint** [comment]
Hi.
For starters: I have added the ability to use a background image for the html section tag, so in settings.json you can add the url('/images/<file_name>.<its_extension>') value to the bg_image key - of course if the background image is in the images directory .

While answering the questions:
1. Yes. The changed getURLparams() function should now correctly call the redirect parameter. But if it turns out that it does not work properly, please let me know.

2. Currently, SSL is almost required for every Captive Portal. This results in some overhead of having a public domain and some complications. Here's why: a domain is needed to create and maintain a certificate, and it's definitely best to use a public certificate. No one will want to accept a self-signed certificate. In OPNsense, you can use the ACME plugin (Let's Encrypt public certificate, it's free, validated every 3 months) but you must have a public domain available. SSL is needed because the vast majority of websites in the world are accessed via the https protocol and in this field Captive Portal must properly bind the session based on DNS - for example: an unregistered user can enter (or simply call from a shortcut in the browser) a redirection address that will always be caught by CP and needs to be handled.

3. Yes, you can use any html tags in your language files, including <a href=\"https://<your_reference>\">any content</a> links. You just have to remember that in json the key and value are always quoted "<key>": "<value>", so any quotes inside the value must be escaped \" as in the example above.
However, if it is an address outside the network of the Captive Portal interface, it will be necessary to at least add the IP addresses of the target server in the CP zone to the Allowed addresses list.

4. There are at least a few factors that affect the performance of the nginx server that hosts the landing page. The CP page load itself is small. You can get rid of the particles.js script and its configuration (index.html file) from the payload
<script src="js/particles.min.js"></script>
<script>particlesJS.load('particles-js', 'config/particles.json', function() {});</script> - but I don't think it will change much but... you can.

In the Captive Portal landing page, no PHP code is executed on the server side - this significantly relieves our server, apart from the required js files, only settings.json files and the target language are downloaded from the json file when loading. When switching the language, only the target language json file is downloaded. However, when the efficiency will be at a high level depends on the number of users and how long they will use access to the CP in the context of how busy the OPNsense system will be with the rest of the work, i.e. providing the Internet with a specific transfer. It is difficult for me to determine how efficient your hardware configuration is in terms of CP. Unfortunately, I don't know enough about your network.

**Comment by SupaYoshi** [comment]
Hey mixmint how can I load a custom image? I have set it in settings.json as a base64 string under logo however I don't know how to load the image i"d like to load it in the 	"footer_isp_info": {

**Comment by mixmint** [comment]
In the language file, you can use the key as the parent of the group (in this case the parent is the "footer_isp_info" key) to which you will substitute an object in which you will define "key": "value" as in this example

`"footer_isp_info": {
		"some_key1": "<img class=\"some-class\" alt=\"some alt\" src=\"images\/image.png\" \/> ISP Name",
		"some_key2": "Street 10, City & Post Code etc.",
		"some_key3": "Other information."
}`

Then each value of such an object will be parsed as html code and rendered in

`<div id="footer_isp_info" class="footer-isp-info">
	<div class="some_key1"><img class="some-class" alt="some alt" src="images\/image.png" /> ISP Name</div>
</div>`

**Comment by mixmint** [comment]
> Hi mixmint
> 
> ```
>  How can I remove check box or make it checked by default ,I need only username and password to login.
> ```
> 
> Thanks

This will require some change in code and configuration. Give me two days... I will tell you what to do once I make the corrections

**Comment by mixmint** [comment]
Ok @mossimo7894, download the latest changes. In the config/settings.json file, in the layout group, you will find the enable_rules key and the assigned boolean value - change it to false, then you will disable the display of consent to the regulations

**Comment by mossimo7894** [comment]
> Ok @mossimo7894, download the latest changes. In the config/settings.json file, in the layout group, you will find the enable_rules key and the assigned boolean value - change it to false, then you will disable the display of consent to the regulations

Thank you very much mixmint.

**Comment by xxcite81** [comment]
Hello @mixmint, Great work. I really like the simplicity of the portal and ease of configuration. My request would be to have;
- A popup or way to get the current session time remaining once you sucessfully login. This would be something similar to // redirect on successful login
if (data['clientState'] == 'AUTHORIZED') {
    window.open("session_popup.html","Session Status & Logout","width=400, height=400");

found here: https://docs.opnsense.org/manual/how-tos/guestnet.html

**Comment by mixmint** [comment]
Hi @xxcite81! 

Please see the current version. The timer remaining until the end of the session is available for authentication via vouchers (I noticed that it is only used in this situation). After logging in with a voucher, you will see a countdown to the end of the session on the Captive Portal page. After the countdown ends, a modal informing about logging out will be presented and then the Captive Portal page will reload. Write if this is what you wanted.
